name: Copy Build

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: run npm install  
        run:  touch generatedfile.txt
      #- name: run build
      #  run:  npm run generate
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-directory: .output/
          destination-github-username: 'devops'
          destination-repository-name: 'pepoman/originalrepo'
          user-email: devops@butchershop.co
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: develop
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
