
name: Push to Repo
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Create local changes
      run: |
          echo "temporary build flag"
          # npm install
          # npm run generate
    - name: Commit files
      run: |
        git config --local user.email "devops@butchershop.co"
        git config --local user.name "devops"
        git add --all
        git commit -m "Build for Server"
        git push --force
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN_GITHUB  }}
        repository: "pepoman/originalrepo"
        branch: ${{ github.ref }}
